{"report":{"reportPrefix":"","assertionsCount":0,"lastError":{"code":"ECONNREFUSED","sessionCreate":true,"showTrace":false,"reportShown":true},"skippedAtRuntime":["Demo test ecosia.org"],"skippedByUser":[],"skipped":["Demo test ecosia.org"],"time":"0.001000","timeMs":1,"completed":{},"completedSections":{"__global_afterEach_hook":{"time":"0.001000","assertions":[],"commands":[],"passed":0,"errors":0,"failed":0,"skipped":0,"tests":0,"status":"fail","startTimestamp":1699780382909,"httpOutput":[["2023-11-12T09:13:02.679Z","  Request POST /session  ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: \u001b[32m&#39;firefox&#39;\u001b[39m } }\n  }"],["2023-11-12T09:13:02.785Z","  Request POST /session  (retry 1) ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: \u001b[32m&#39;firefox&#39;\u001b[39m } }\n  }"],["2023-11-12T09:13:02.889Z","  Request POST /session  (retry 2) ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: \u001b[32m&#39;firefox&#39;\u001b[39m } }\n  }"]],"timeMs":1,"endTimestamp":1699780382910}},"errmessages":[" \u001b[31mAn error occurred while creating a new GeckoDriver session: Connection refused to localhost:4444. If the Webdriver/Selenium service is managed by Nightwatch, check if \"start_process\" is set to \"true\".\u001b[39m"],"testsCount":0,"skippedCount":1,"failedCount":0,"errorsCount":1,"passedCount":0,"group":"","modulePath":"/Users/davidko/Work/nightwatch-sandbox/dist/tests/02-find-and-log.js","startTimestamp":"Sun, 12 Nov 2023 09:13:02 GMT","endTimestamp":"Sun, 12 Nov 2023 09:13:02 GMT","sessionCapabilities":{"browserName":"firefox","name":"Baseline Test"},"sessionId":"","projectName":"","buildName":"","testEnv":"default","isMobile":false,"status":"fail","host":"localhost","name":"Baseline Test","tags":[],"tests":0,"failures":0,"errors":1,"httpOutput":[["2023-11-12T09:13:02.679Z","  Request POST /session  ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: <span style=\"color:#0A0\">&#39;firefox&#39;<span style=\"color:#FFF\"> } }\n  }</span></span>"],["2023-11-12T09:13:02.785Z","  Request POST /session  (retry 1) ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: <span style=\"color:#0A0\">&#39;firefox&#39;<span style=\"color:#FFF\"> } }\n  }</span></span>"],["2023-11-12T09:13:02.889Z","  Request POST /session  (retry 2) ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: <span style=\"color:#0A0\">&#39;firefox&#39;<span style=\"color:#FFF\"> } }\n  }</span></span>"]],"rawHttpOutput":[["2023-11-12T09:13:02.679Z","  Request POST /session  ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: 'firefox' } }\n  }"],["2023-11-12T09:13:02.785Z","  Request POST /session  (retry 1) ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: 'firefox' } }\n  }"],["2023-11-12T09:13:02.889Z","  Request POST /session  (retry 2) ","{\n     capabilities: { firstMatch: [ {} ], alwaysMatch: { browserName: 'firefox' } }\n  }"]],"globalErrorRegister":[" \u001b[31mAn error occurred while creating a new GeckoDriver session: Connection refused to localhost:4444. If the Webdriver/Selenium service is managed by Nightwatch, check if \"start_process\" is set to \"true\".\u001b[39m"]},"name":"02-find-and-log","httpOutput":[],"systemerr":" An error occurred while creating a new GeckoDriver session: Connection refused to localhost:4444. If the Webdriver/Selenium service is managed by Nightwatch, check if \"start_process\" is set to \"true\"."}